"""Render the commit-safe Stage 11 metrics report from Stage 10 JSON."""

from __future__ import annotations

import argparse
import hashlib
import json
from collections.abc import Mapping, Sequence
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = PROJECT_ROOT / "evaluation" / "results" / "stage10-final.json"
DEFAULT_OUTPUT = PROJECT_ROOT / "docs" / "evaluation-report.md"


def _mapping(value: object, name: str) -> Mapping[str, object]:
    if not isinstance(value, Mapping):
        raise TypeError(f"{name} must be a JSON object")
    return value


def _text(value: object, name: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{name} must be a non-empty string")
    return value


def _number(value: object, name: str) -> int | float:
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        raise TypeError(f"{name} must be numeric")
    return value


def _flag(value: object, name: str) -> str:
    if not isinstance(value, bool):
        raise TypeError(f"{name} must be boolean")
    return "PASS" if value else "FAIL"


def _pct(value: object, name: str) -> str:
    return f"{float(_number(value, name)):.2%}"


def _count(value: object, name: str) -> int:
    number = _number(value, name)
    if int(number) != number:
        raise ValueError(f"{name} must be an integer")
    return int(number)


def load_result(source: Path) -> tuple[dict[str, object], str]:
    raw = source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    value = json.loads(raw.decode("utf-8"))
    result = dict(_mapping(value, "Stage 10 result"))
    if result.get("stage") != "stage10":
        raise ValueError("source is not a Stage 10 result")
    if result.get("final_verdict") not in {"COMPLETE", "PASS"}:
        raise ValueError("Stage 10 result is not a completed measured result")
    return result, digest


def render_report(result: Mapping[str, object], source_sha256: str) -> str:
    dataset = _mapping(result.get("dataset"), "dataset")
    provenance = _mapping(dataset.get("approval_provenance"), "approval_provenance")
    quality = _mapping(result.get("quality"), "quality")
    triage = _mapping(quality.get("triage"), "quality.triage")
    tools = _mapping(quality.get("tool_selection"), "quality.tool_selection")
    arguments = _mapping(quality.get("critical_arguments"), "quality.critical_arguments")
    trajectory = _mapping(quality.get("trajectory"), "quality.trajectory")
    date_time = _mapping(quality.get("date_time"), "quality.date_time")
    security = _mapping(_mapping(result.get("security"), "security").get("observed_model"), "security.observed_model")
    checkpoint = _mapping(result.get("checkpoint"), "checkpoint")
    memory = _mapping(result.get("memory"), "memory")
    idempotency = _mapping(result.get("idempotency"), "idempotency")
    provider = _mapping(result.get("provider_side_effect_counts"), "provider_side_effect_counts")
    tests = _mapping(result.get("test_results"), "test_results")
    pytest_result = _mapping(tests.get("full_pytest"), "test_results.full_pytest")
    postgres_result = _mapping(tests.get("postgresql_integration"), "test_results.postgresql_integration")
    restart = _mapping(result.get("restart"), "restart")

    triage_confusion = _mapping(triage.get("confusion_matrix"), "triage.confusion_matrix")
    matrix_lines = []
    for actual in ("ACTION_REQUIRED", "IGNORE", "NOTIFY"):
        row = _mapping(triage_confusion.get(actual), f"triage.confusion_matrix.{actual}")
        matrix_lines.append(
            f"| `{actual}` | {_count(row.get('ACTION_REQUIRED'), actual)} | "
            f"{_count(row.get('IGNORE'), actual)} | {_count(row.get('NOTIFY'), actual)} |"
        )

    return f"""# Stage 10 observed evaluation report

This document is generated by `scripts/generate_final_metrics_report.py` from
the redacted machine-readable source `evaluation/results/stage10-final.json`.
It contains observed measurements only; it does not rerun DeepSeek and does
not make provider writes.

## Provenance

| Field | Value |
|---|---|
| Source SHA-256 | `{source_sha256}` |
| Evaluation timestamp | `{_text(result.get('evaluation_timestamp'), 'evaluation_timestamp')}` |
| Dataset hash | `{_text(result.get('dataset_version'), 'dataset_version')}` |
| Dataset cases | `{_count(dataset.get('dataset_case_count'), 'dataset_case_count')}` |
| Approved cases | `{_count(dataset.get('approved_cases'), 'approved_cases')}` |
| Approval provenance | `{_text(provenance.get('status'), 'approval_provenance.status')}`, `{_count(provenance.get('record_count'), 'approval_provenance.record_count')}` records |
| Stage 10 verdict | `{_text(result.get('final_verdict'), 'final_verdict')}` |

## Observed quality

### Triage

| Metric | Value |
|---|---:|
| Accuracy | {_pct(triage.get('accuracy'), 'triage.accuracy')} |
| Macro-F1 | {_pct(triage.get('macro_f1'), 'triage.macro_f1')} |
| Correct / measured | `{_count(triage.get('correct'), 'triage.correct')} / {_count(triage.get('measured'), 'triage.measured')}` |

Confusion matrix (actual rows, expected columns):

| Actual \\ Expected | ACTION_REQUIRED | IGNORE | NOTIFY |
|---|---:|---:|---:|
{chr(10).join(matrix_lines)}

### Tool selection

| Metric | Value |
|---|---:|
| Exact match | {_pct(tools.get('exact_match'), 'tool_selection.exact_match')} (`{_count(tools.get('exact_matches'), 'tool_selection.exact_matches')} / {_count(tools.get('measured'), 'tool_selection.measured')}`) |
| Precision / recall / F1 | {_pct(tools.get('precision'), 'tool_selection.precision')} / {_pct(tools.get('recall'), 'tool_selection.recall')} / {_pct(tools.get('f1'), 'tool_selection.f1')} |
| Forbidden tool invocations | `{_count(tools.get('forbidden_tool_count'), 'tool_selection.forbidden_tool_count')}` |

### Arguments, trajectory and time

| Measure | Result |
|---|---:|
| Critical arguments | `{_count(arguments.get('matched_fields'), 'critical_arguments.matched_fields')} / {_count(arguments.get('measured_fields'), 'critical_arguments.measured_fields')}` ({_pct(arguments.get('accuracy'), 'critical_arguments.accuracy')}) |
| Trajectory | `{_count(trajectory.get('passed'), 'trajectory.passed')} / {_count(trajectory.get('measured'), 'trajectory.measured')}` ({_pct(trajectory.get('accuracy'), 'trajectory.accuracy')}) |
| Date/time applicable | `{_count(date_time.get('passed'), 'date_time.passed')} / {_count(date_time.get('measured'), 'date_time.measured')}` ({_pct(date_time.get('accuracy'), 'date_time.accuracy')}) |

### Security

| Measure | Result |
|---|---:|
| Observed security cases | `{_count(security.get('passed'), 'security.passed')} / {_count(security.get('measured'), 'security.measured')}` |
| Security violations | `{_count(security.get('security_violations'), 'security.security_violations')}` |
| Hard gate | `{_flag(security.get('hard_gate_passed'), 'security.hard_gate_passed')}` |

## Reliability and provider safety

| Gate | Evidence |
|---|---|
| Checkpoint / cross-process restart | `{restart.get('checkpoint')}` / `{checkpoint.get('process_restart_postgresql')}` |
| Memory restart | `{restart.get('memory')}` |
| Account isolation | `{_flag(memory.get('checks', {}).get('account_isolated'), 'memory.checks.account_isolated')}` |
| Idempotency / replay | `{idempotency.get('replay_status')}`, unknown blocks retry: `{_flag(idempotency.get('checks', {}).get('unknown_blocks_retry'), 'idempotency.checks.unknown_blocks_retry')}` |
| ClickUp POST during benchmark | `{_count(provider.get('observed_clickup_post'), 'observed_clickup_post')}` |
| Calendar insert during benchmark | `{_count(provider.get('observed_google_calendar_insert'), 'observed_google_calendar_insert')}` |
| Real provider writes | `{_count(provider.get('observed_real_provider_writes'), 'observed_real_provider_writes')}` |

`fixture_provider_writes` is an offline test-double call and is not a real
provider write.

## Engineering baseline from the same result

| Check | Result |
|---|---|
| Full pytest | `{_text(pytest_result.get('status'), 'full_pytest.status')}` — `{_count(pytest_result.get('passed'), 'full_pytest.passed')} passed`, `{_count(pytest_result.get('skipped'), 'full_pytest.skipped')} expected live skips` |
| PostgreSQL integration | `{_text(postgres_result.get('status'), 'postgresql_integration.status')}` — `{_count(postgres_result.get('passed'), 'postgresql_integration.passed')} / {_count(postgres_result.get('tests'), 'postgresql_integration.tests')}` |
| Stage 10 report | `{_text(result.get('final_verdict'), 'final_verdict')}` |

Alembic revision and Stage 11 packaging checks are measured by the Stage 11
acceptance command, not inferred from this Stage 10 result.

## Interpretation boundary

These are observed benchmark and deterministic regression measurements. They
are not target metrics, a claim of arbitrary-email generalization, or evidence
that a real ClickUp/Calendar write happened during evaluation.
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    result, digest = load_result(args.source)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_report(result, digest), encoding="utf-8", newline="\n")
    print(json.dumps({"source": str(args.source), "source_sha256": digest, "output": str(args.output)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
